### model
model_name_or_path: [!!!add the model path here!!!]
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/ds_zero3_offload_hy.json

### dataset
dataset: [!!!add the data set name here!!!]
template: hunyuan
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true


### output
output_dir: saves/hunyuan/full/
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
average_tokens_across_devices: false
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
